const productProteins = {
  productProteins: [
    { name: "Agnello" },
    { name: "Anatra" },
    { name: "Aringa" },
    { name: "Assortite" },
    { name: "Bufalo" },
    { name: "Carne" },
    { name: "Cervo" },
    { name: "Cinghiale" },
    { name: "Coniglio" },
    { name: "Lepre" },
    { name: "Maiale" },
    { name: "Manzo" },
    { name: "Merluzzo" },
    { name: "Oca" },
    { name: "Pesce" },
    { name: "Pesce Bianco" },
    { name: "Pollame" },
    { name: "Pollo" },
    { name: "Prosciutto" },
    { name: "Prosciutto crudo" },
    { name: "Quaglia" },
    { name: "Riso" },
    { name: "Salmone" },
    { name: "Tacchino" },
    { name: "Tonno" },
    { name: "Trota" },
    { name: "Uova" },
    { name: "Verdura" },
  ],
};

export default productProteins;
