const productProteins = [
  { name: "Agnello", slug: "agnello" },
  { name: "Anatra", slug: "anatra" },
  { name: "Aringa", slug: "aringa" },
  { name: "Assortite", slug: "assortite" },
  { name: "Bufalo", slug: "bufalo" },
  { name: "Carne", slug: "carne" },
  { name: "Cervo", slug: "cervo" },
  { name: "Cinghiale", slug: "cinghiale" },
  { name: "Coniglio", slug: "coniglio" },
  { name: "Lepre", slug: "lepre" },
  { name: "Maiale", slug: "maiale" },
  { name: "Manzo", slug: "manzo" },
  { name: "Merluzzo", slug: "merluzzo" },
  { name: "Oca", slug: "oca" },
  { name: "Pesce", slug: "pesce" },
  { name: "Pesce Bianco", slug: "pesce-bianco" },
  { name: "Pollame", slug: "pollame" },
  { name: "Pollo", slug: "pollo" },
  { name: "Prosciutto", slug: "prosciutto" },
  { name: "Prosciutto crudo", slug: "prosciutto-crudo" },
  { name: "Quaglia", slug: "quaglia" },
  { name: "Riso", slug: "riso" },
  { name: "Salmone", slug: "salmone" },
  { name: "Tacchino", slug: "tacchino" },
  { name: "Tonno", slug: "tonno" },
  { name: "Trota", slug: "trota" },
  { name: "Uova", slug: "uova" },
  { name: "Verdura", slug: "verdura" },
];

export default productProteins;
