const addressesData = [
  {
    street: "Via Roma 15",
    city: "Milano",
    zipCode: "20121",
    country: "Italia",
    fullName: "Mario Rossi",
    isDefault: true,
  },
  {
    street: "Corso Vittorio Emanuele II 25",
    city: "Torino",
    zipCode: "10121",
    country: "Italia",
    fullName: "Giovanna Bianchi",
    isDefault: false,
  },
  {
    street: "Piazza della Signoria 10",
    city: "Firenze",
    zipCode: "50122",
    country: "Italia",
    fullName: "Luca Verdi",
    isDefault: false,
  },
  {
    street: "Via Garibaldi 20",
    city: "Genova",
    zipCode: "16124",
    country: "Italia",
    fullName: "Elena Ferrari",
    isDefault: false,
  },
  {
    street: "Viale dei Colli 45",
    city: "Napoli",
    zipCode: "80122",
    country: "Italia",
    fullName: "Riccardo Neri",
    isDefault: true,
  },
  {
    street: "Piazza Duomo 2",
    city: "Bologna",
    zipCode: "40121",
    country: "Italia",
    fullName: "Francesca Romano",
    isDefault: false,
  },
  {
    street: "Via Dante 99",
    city: "Palermo",
    zipCode: "90133",
    country: "Italia",
    fullName: "Giorgio Marini",
    isDefault: false,
  },
  {
    street: "Via Libertà 55",
    city: "Catania",
    zipCode: "95127",
    country: "Italia",
    fullName: "Alessia Conti",
    isDefault: false,
  },
];
export default addressesData;
