import ROLES from "./roles";

export const USER_STATUS_ACTIVATION = {
  ACTIVE: "ACTIVE",
  PENDING: "PENDING",
  INACTIVE: "INACTIVE",
  BANNED: "BANNED",
};

export const USER_STATUS = process.env.USER_STATUS
  ? process.env.USER_STATUS.split(",")
  : [
      USER_STATUS_ACTIVATION.ACTIVE,
      USER_STATUS_ACTIVATION.PENDING,
      USER_STATUS_ACTIVATION.INACTIVE,
      USER_STATUS_ACTIVATION.BANNED,
    ];
